### ISSUE TITLE
Funciona¿?

### ISSUE THREAD

**Issue by knoopx** [ritxi/sermepa_web_tpv#6]
Hei tio, com vas? La generació de la signatura funciona? Porto unes quantes hores donant-me de cops contra la paret i estic segur que es culpa de SERMEPA. Tens això rutllant en producció?

**Comment by ritxi** [comment]
Hola!

Sí, sí. La signatura aquesta funciona bé. Ara mateix la tinc rulant a producció. Vaig tenir 1000 problemes, però el que hi ha ara xuta bé.

Si fas servir la gema, funciona 100%. Estàs fent servir aquest codi? Fa pocs dies vaig fer una petita actualització.

**Comment by knoopx** [comment]
He contactat els de SERMEPA, aviam què hem diuen, segur que es cosa seva. Merci tio!
