### ISSUE TITLE
signature generation (generación de la firma)

### ISSUE THREAD

**Issue by xploshioOn** [ritxi/sermepa_web_tpv#7]
Hi, I am using this gem, everything is ok with generating the options, but the signature or DS_Merchant_MerchantSignature isn't in the params, all the another params are fine, but this  don't come in the options, I followed all the instructions in the readme.

I tried generating the signature manually and it works but how can I generate the signature with the gem? or why isn't generated y default? 

thanks.

Estoy usando la gema, todos los parametros se generan sin problemas, pero por alguna razon, la firma no es generada, no aparece en las opciones, seguí todos los pasos del tutorial, tienes idea de cual puede ser el problema? o decirme como puedo generar la firma para pasarla como otro parametro que se envia en el form? saludos.

this is the code in my controller

```
transaction = Transaction.new(amount: 1000, user_id:current_user.id)
sermepa_request = SermepaWebTpv::Request.new(transaction, params[:description])
sermepa_request.transact {|t| t.save }
@options = sermepa_request.options
@url = sermepa_request.bank_url

```

**Comment by ritxi** [comment]
This code should work fine.

In my controller there is basically the same:

``` ruby
request = SermepaWebTpv::Request.new(transaction, "#{application.activity.name}: #{persones}")
request.transact { |trans| trans.save }
render json: { payment_options: request.params, url: request.bank_url  }
```

This should generate a json like that: 

``` json
{:payment_options=>{"Ds_SignatureVersion"=>"HMAC_SHA256_V1", "Ds_MerchantParameters"=>"eyJEc19NZXJjaGFudF9UaXR1bGFyIjoiQXNzZW1ibGVhIE5hY2lvbmFsIENhdGFsYW5hIC0gU0JEeEkiLCJEc19NZXJjaGFudF9VcmxLTyI6Imh0dHA6Ly9zYmR4aS1zdGFnaW5nLmhlcm9rdWFwcC5jb20vdHJhbnNhY3Rpb25zL2ZhaWx1cmUiLCJEc19NZXJjaGFudF9VcmxPSyI6Imh0dHA6Ly9zYmR4aS1zdGFnaW5nLmhlcm9rdWFwcC5jb20vdHJhbnNhY3Rpb25zL3N1Y2Nlc3MiLCJEc19NZXJjaGFudF9BbW91bnQiOiIxMjAwIiwiRHNfTWVyY2hhbnRfT3JkZXIiOiIxNjAzMjQyMzM1NDEiLCJEc19NZXJjaGFudF9Qcm9kdWN0RGVzY3JpcHRpb24iOiJUcmFuc2FjdGlvbiB0ZXN0IiwiRHNfTWVyY2hhbnRfQ3VycmVuY3kiOjk3OCwiRHNfTWVyY2hhbnRfTWVyY2hhbnRDb2RlIjoiMzI3MjMxODE3IiwiRHNfTWVyY2hhbnRfVGVybWluYWwiOjEsIkRzX01lcmNoYW50X1RyYW5zYWN0aW9uVHlwZSI6MCwiRHNfTWVyY2hhbnRfQ29uc3VtZXJMYW5ndWFnZSI6IjAwMyIsIkRzX01lcmNoYW50X01lcmNoYW50VVJMIjoiaHR0cDovL3NiZHhpLXN0YWdpbmcuaGVyb2t1YXBwLmNvbS90cmFuc2FjdGlvbnMvdmFsaWRhdGUifQ==", "Ds_Signature"=>"IjGNMD5POKeMgaCE3xQlrr/p6ObsZ9tyq7OB0Pdo5EY="}, :url=>"https://sis-t.redsys.es:25443/sis/realizarPago"}
```

With basically Ds_SignatureVersion, Ds_MerchantParameters, Ds_Signature.

Sorry for the delay to answer, I hope it helps.

**Comment by xploshioOn** [comment]
for some reason the signature is not generated by default, I generated that manually and added that to the object, Ill close the issue, thanks for the answer.
