### ISSUE TITLE
URI::BadURIError (both URI are relative)

### ISSUE THREAD

**Issue by hyperrjas** [ritxi/sermepa_web_tpv#8]
Hola he actualizado la versión desde la 0.0.2 a la versión 0.1.3 y obtengo este error en la solicitud.

URI::BadURIError (both URI are relative).

Este es mi fragmento de código para realizar la solicitud que funciona bien con la versión 0.0.2

```
transaction = CardPayment.new(amount: order_amount(params[:period], params[:locale]), teacher_id: teacher_id,
                                  sender_email: sender_email, course_id: params[:course_id], currency: currency, locale: params[:locale])
    request = SermepaWebTpv::Request.new(transaction, "#{params[:period]}")
    request.transact {|t| t.save }
    options = request.options
```

Obtengo el error en la línea `options = request.options`

Hay algún problema con la firma en esta nueva versión?

Gracias.

**Comment by ritxi** [comment]
Que yo sepa no hay ningún problema. Todo lo que podía haber lo solucioné.

Pero el error pinta que te falta definir el `response_host`

``` ruby
module MyApp
  class Application < Rails::Application
    config.web_tpv.response_host = 'https://my_application_host.com'
  end
end
```

Es una suposición, pero si en la traza de error sale esta [linea](https://github.com/ritxi/sermepa_web_tpv/blob/master/lib/sermepa_web_tpv/request.rb#L66) casi seguro que es el motivo del error.

**Comment by hyperrjas** [comment]
Gracias ahí estaba el error, yo lo tenía sin el `https://`. Sin embargo me da error de firma `<!--SIS0020:-->`
En el formulario de envio la firma va vacía en esta nueva versión.
`<input id="Ds_Merchant_MerchantSignature" name="Ds_Merchant_MerchantSignature" type="hidden" value="">`

Nota. Veo que la firma se genera en esta nueva versión en `request.params` y no en `request.options`.

Me daba este error:

`LoadError (cannot load such file -- mcrypt)`

He instalado mcrypt `https://github.com/kingpong/ruby-mcrypt` y ahora obtengo este error:

`Mcrypt::InvalidKeyError (Key length 15 is not supported by tripledes.)`

Muchas gracias nuevamente :)

Un saludo!
